# src/ava/gui/node_viewer/__init__.py
"""
The Node Viewer package provides a real-time, animated visualization of the
project structure as it's being planned and generated by the AI.
"""

from .project_node import ProjectNode
from .project_visualizer_window import ProjectVisualizerWindow

__all__ = [
    "ProjectNode",
    "ProjectVisualizerWindow",
]